### ISSUE TITLE
bus admin section

### ISSUE THREAD

**Issue by ruhulaminrul** [ruhulaminrul/E-Ticketing-bus-train-and-plane#21]
bus----- id, bus_no,   total-seat,  company-id

counter ---- id name company-id city_id
seat_status - id name only migration and seed

**Comment by Sourovahmad** [comment]
seat - id name --- migration and seed

**Comment by ruhulaminrul** [comment]
DB::table('seats')->insert([
            [
                'name' => 'A1'
            ],
            [
                'name' => 'A2'
            ],
            [
                'name' => 'A3'
            ],
            [
                'name' => 'A4'
            ],
            [
                'name' => 'B1'
            ],
            [
                'name' => 'B2'
            ],
            [
                'name' => 'B3'
            ],
            [
                'name' => 'B4'
            ],
            [
                'name' => 'C1'
            ],
            [
                'name' => 'C2'
            ],
            [
                'name' => 'C3'
            ],
            [
                'name' => 'C4'
            ],
            [
                'name' => 'D1'
            ],
            [
                'name' => 'D2'
            ],
            [
                'name' => 'D3'
            ],
            [
                'name' => 'D4'
            ],
            [
                'name' => 'E1'
            ],
            [
                'name' => 'E2'
            ],
            [
                'name' => 'E3'
            ],
            [
                'name' => 'E4'
            ],
            [
                'name' => 'F1'
            ],
            [
                'name' => 'F2'
            ],
            [
                'name' => 'F3'
            ],
            [
                'name' => 'F4'
            ],
            [
                'name' => 'G1'
            ],
            [
                'name' => 'G2'
            ],
            [
                'name' => 'G3'
            ],
            [
                'name' => 'G4'
            ],
            [
                'name' => 'H1'
            ],
            [
                'name' => 'H2'
            ],
            [
                'name' => 'H3'
            ],
            [
                'name' => 'H4'
            ],
            [
                'name' => 'I1'
            ],
            [
                'name' => 'I2'
            ],
            [
                'name' => 'I3'
            ],
            [
                'name' => 'I4'
            ],


        ]);

        
        DB::table('statuses')->insert([
            [
                'name' => 'Available',
                'description' => 'Not Buy Yet'
            ],
            [
                'name' => 'pending',
                'description' => 'Requested but not payment yet'
            ],
            [
                'name' => 'Booked',
                'description' => 'Some already one buy this ticket'
            ],

        ]);

**Comment by ruhulaminrul** [comment]
Schema::create('statuses', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name');
            $table->string('description');
            $table->timestamps();
        });

**Comment by ruhulaminrul** [comment]
Schema::create('seats', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name');
            $table->timestamps();
        });

**Comment by ruhulaminrul** [comment]
bus counter automatic select company id,

**Comment by Sourovahmad** [comment]
added bus, counter , seat status
